// Taxonomie de métiers/situations pour le sélecteur "Ton métier ou ta
// situation actuelle" du profil candidat — remplace le champ texte libre
// "Titre professionnel" par une liste organisée par domaine, chacun avec
// une icône, plus une option "Saisir un autre métier" pour tout ce qui ne
// s'y trouve pas. Demande explicite de l'utilisateur, avec une capture de
// référence pour la structure ; liste étendue à sa demande ("il faut tous
// les métiers") pour couvrir un éventail bien plus large par catégorie.
export const CATEGORIES_METIERS = [
  {
    id: "situation_actuelle",
    label: "Situation actuelle",
    icone: "🌱",
    metiers: [
      { label: "En recherche d'emploi", emoji: "🔍" },
      { label: "Je ne travaille pas encore", emoji: "🌱" },
      { label: "Étudiant", emoji: "🎓" },
      { label: "Stagiaire", emoji: "📎" },
      { label: "Apprenti", emoji: "🧰" },
      { label: "Au foyer", emoji: "🏠" },
      { label: "Bénévole", emoji: "🙌" },
      { label: "En congé parental", emoji: "🍼" },
      { label: "Retraité", emoji: "🌅" },
    ],
  },
  {
    id: "sante",
    label: "Santé",
    icone: "⚕️",
    metiers: [
      { label: "Médecin généraliste", emoji: "🩺" },
      { label: "Médecin spécialiste", emoji: "🩺" },
      { label: "Chirurgien", emoji: "🔪" },
      { label: "Radiologue", emoji: "🩻" },
      { label: "Anesthésiste", emoji: "💤" },
      { label: "Infirmier", emoji: "💉" },
      { label: "Pharmacien", emoji: "💊" },
      { label: "Préparateur en pharmacie", emoji: "🧴" },
      { label: "Dentiste", emoji: "🦷" },
      { label: "Sage-femme", emoji: "🤱" },
      { label: "Kinésithérapeute", emoji: "🦴" },
      { label: "Ostéopathe", emoji: "🦵" },
      { label: "Orthophoniste", emoji: "🗨️" },
      { label: "Psychologue", emoji: "🧠" },
      { label: "Psychiatre", emoji: "🧠" },
      { label: "Nutritionniste / Diététicien", emoji: "🥗" },
      { label: "Opticien", emoji: "👓" },
      { label: "Vétérinaire", emoji: "🐾" },
      { label: "Technicien de laboratoire", emoji: "🧪" },
      { label: "Aide-soignant", emoji: "🧑‍⚕️" },
      { label: "Ambulancier", emoji: "🚑" },
      { label: "Tradipraticien", emoji: "🌿" },
      { label: "Agent de santé communautaire", emoji: "🏥" },
    ],
  },
  {
    id: "tech_numerique",
    label: "Tech & Numérique",
    icone: "💻",
    metiers: [
      { label: "Ingénieur logiciel", emoji: "💻" },
      { label: "Développeur web", emoji: "🌐" },
      { label: "Développeur mobile", emoji: "📱" },
      { label: "Développeur backend", emoji: "🗄️" },
      { label: "Développeur frontend", emoji: "🖌️" },
      { label: "Ingénieur DevOps", emoji: "🔄" },
      { label: "Architecte logiciel", emoji: "🏛️" },
      { label: "Data scientist", emoji: "📊" },
      { label: "Data analyst", emoji: "📉" },
      { label: "Technicien informatique", emoji: "🖥️" },
      { label: "Administrateur réseau", emoji: "📡" },
      { label: "Administrateur systèmes", emoji: "🗃️" },
      { label: "Expert cybersécurité", emoji: "🔒" },
      { label: "Testeur QA", emoji: "🐞" },
      { label: "Chef de produit", emoji: "📦" },
      { label: "Designer UX/UI", emoji: "🎨" },
      { label: "Community manager", emoji: "📲" },
      { label: "Webmaster", emoji: "🕸️" },
      { label: "Monteur de réseaux télécoms", emoji: "📶" },
    ],
  },
  {
    id: "ingenierie",
    label: "Ingénierie",
    icone: "⚙️",
    metiers: [
      { label: "Ingénieur civil", emoji: "🏗️" },
      { label: "Ingénieur mécanique", emoji: "⚙️" },
      { label: "Ingénieur électrique", emoji: "🔌" },
      { label: "Ingénieur électronique", emoji: "🔋" },
      { label: "Ingénieur chimiste", emoji: "⚗️" },
      { label: "Ingénieur biomédical", emoji: "🩻" },
      { label: "Ingénieur en environnement", emoji: "♻️" },
      { label: "Ingénieur des mines", emoji: "⛏️" },
      { label: "Ingénieur pétrolier", emoji: "🛢️" },
      { label: "Ingénieur aéronautique", emoji: "✈️" },
      { label: "Architecte", emoji: "📐" },
      { label: "Urbaniste", emoji: "🏙️" },
      { label: "Ingénieur industriel", emoji: "🏭" },
      { label: "Agronome", emoji: "🌾" },
      { label: "Géologue", emoji: "🪨" },
      { label: "Géomètre / Topographe", emoji: "🧭" },
      { label: "Métreur / Conducteur de travaux", emoji: "📏" },
    ],
  },
  {
    id: "business_finance",
    label: "Business & Finance",
    icone: "💼",
    metiers: [
      { label: "Comptable", emoji: "🧮" },
      { label: "Auditeur", emoji: "📋" },
      { label: "Contrôleur de gestion", emoji: "🧾" },
      { label: "Banquier", emoji: "🏦" },
      { label: "Analyste financier", emoji: "📈" },
      { label: "Trader", emoji: "💹" },
      { label: "Actuaire", emoji: "🧠" },
      { label: "Économiste", emoji: "🌍" },
      { label: "Entrepreneur", emoji: "🚀" },
      { label: "Directeur / Manager", emoji: "🗂️" },
      { label: "Consultant", emoji: "🤝" },
      { label: "Responsable RH", emoji: "👥" },
      { label: "Recruteur", emoji: "🧑‍💼" },
      { label: "Marketing / Communication", emoji: "📣" },
      { label: "Chargé de clientèle", emoji: "📞" },
      { label: "Commercial", emoji: "🎁" },
      { label: "Négociateur", emoji: "🤝" },
      { label: "Caissier", emoji: "🧾" },
      { label: "Agent immobilier", emoji: "🏡" },
      { label: "Assureur", emoji: "🛡️" },
      { label: "Import / Export", emoji: "🚢" },
      { label: "Acheteur", emoji: "🛒" },
      { label: "Gestionnaire de stock", emoji: "📦" },
      { label: "Micro-entrepreneur / Auto-entrepreneur", emoji: "🧾" },
    ],
  },
  {
    id: "droit_public",
    label: "Droit & Public",
    icone: "⚖️",
    metiers: [
      { label: "Avocat", emoji: "⚖️" },
      { label: "Magistrat / Juge", emoji: "👨‍⚖️" },
      { label: "Notaire", emoji: "📜" },
      { label: "Huissier de justice", emoji: "📨" },
      { label: "Greffier", emoji: "🗂️" },
      { label: "Juriste", emoji: "📚" },
      { label: "Policier", emoji: "👮" },
      { label: "Gendarme", emoji: "🎖️" },
      { label: "Militaire", emoji: "🎖️" },
      { label: "Pompier", emoji: "🚒" },
      { label: "Fonctionnaire", emoji: "🏛️" },
      { label: "Élu local / Homme politique", emoji: "🗳️" },
      { label: "Diplomate", emoji: "🌐" },
      { label: "Douanier", emoji: "🛂" },
      { label: "Garde forestier", emoji: "🌲" },
    ],
  },
  {
    id: "education",
    label: "Éducation",
    icone: "🎓",
    metiers: [
      { label: "Instituteur / Maître d'école", emoji: "🍎" },
      { label: "Enseignant collège/lycée", emoji: "📗" },
      { label: "Professeur d'université", emoji: "🎓" },
      { label: "Formateur professionnel", emoji: "📚" },
      { label: "Conseiller pédagogique", emoji: "🧑‍🏫" },
      { label: "Éducateur spécialisé", emoji: "🧑‍🤝‍🧑" },
      { label: "Animateur socio-éducatif", emoji: "🎪" },
      { label: "Moniteur auto-école", emoji: "🚗" },
      { label: "Chercheur", emoji: "🔬" },
      { label: "Traducteur / Interprète", emoji: "🗣️" },
      { label: "Bibliothécaire", emoji: "📖" },
      { label: "Maître coranique / Enseignant religieux", emoji: "📿" },
    ],
  },
  {
    id: "metiers_artisanat",
    label: "Métiers & Artisanat",
    icone: "🔧",
    metiers: [
      { label: "Électricien", emoji: "💡" },
      { label: "Plombier", emoji: "🔧" },
      { label: "Mécanicien auto/moto", emoji: "🚗" },
      { label: "Menuisier", emoji: "🪚" },
      { label: "Maçon", emoji: "🧱" },
      { label: "Carreleur", emoji: "🀄" },
      { label: "Plâtrier / Peintre en bâtiment", emoji: "🎨" },
      { label: "Vitrier", emoji: "🪟" },
      { label: "Soudeur / Métallier", emoji: "🔥" },
      { label: "Forgeron", emoji: "🔨" },
      { label: "Chaudronnier", emoji: "🛠️" },
      { label: "Couturier / Tailleur", emoji: "✂️" },
      { label: "Cordonnier", emoji: "👞" },
      { label: "Bijoutier / Orfèvre", emoji: "💍" },
      { label: "Horloger", emoji: "⏱️" },
      { label: "Coiffeur / Barbier", emoji: "💇" },
      { label: "Esthéticienne", emoji: "💅" },
      { label: "Boulanger / Pâtissier", emoji: "🥖" },
      { label: "Cuisinier", emoji: "🍳" },
      { label: "Réparateur électronique", emoji: "🔌" },
      { label: "Vulcanisateur", emoji: "🛞" },
      { label: "Tapissier", emoji: "🛋️" },
      { label: "Teinturier / Blanchisseur", emoji: "🧺" },
      { label: "Agent magasinier", emoji: "📦" },
      { label: "Agent de sécurité", emoji: "🛡️" },
    ],
  },
  {
    id: "agriculture_environnement",
    label: "Agriculture & Environnement",
    icone: "🌾",
    metiers: [
      { label: "Agriculteur / Cultivateur", emoji: "🌿" },
      { label: "Maraîcher", emoji: "🥬" },
      { label: "Éleveur", emoji: "🐄" },
      { label: "Pêcheur", emoji: "🎣" },
      { label: "Aquaculteur", emoji: "🐟" },
      { label: "Apiculteur", emoji: "🐝" },
      { label: "Jardinier / Paysagiste", emoji: "🌳" },
      { label: "Technicien agricole", emoji: "🚜" },
      { label: "Forestier / Sylviculteur", emoji: "🌲" },
      { label: "Écologiste / Environnementaliste", emoji: "♻️" },
    ],
  },
  {
    id: "transport_logistique",
    label: "Transport & Logistique",
    icone: "🚚",
    metiers: [
      { label: "Chauffeur particulier / Taxi", emoji: "🚕" },
      { label: "Chauffeur de bus/car", emoji: "🚌" },
      { label: "Chauffeur poids lourd", emoji: "🚛" },
      { label: "Livreur / Coursier", emoji: "🛵" },
      { label: "Conducteur de moto-taxi", emoji: "🏍️" },
      { label: "Pilote", emoji: "🛫" },
      { label: "Marin / Matelot", emoji: "⚓" },
      { label: "Docker / Manutentionnaire", emoji: "📦" },
      { label: "Transitaire / Logisticien", emoji: "🚢" },
      { label: "Agent de manutention aéroportuaire", emoji: "🛄" },
    ],
  },
  {
    id: "creation_medias",
    label: "Création & Médias",
    icone: "🎨",
    metiers: [
      { label: "Journaliste", emoji: "📰" },
      { label: "Animateur radio/TV", emoji: "🎙️" },
      { label: "Réalisateur", emoji: "🎥" },
      { label: "Monteur vidéo", emoji: "🎞️" },
      { label: "Photographe", emoji: "📷" },
      { label: "Graphiste", emoji: "✏️" },
      { label: "Illustrateur", emoji: "🖍️" },
      { label: "Artiste peintre / Sculpteur", emoji: "🎭" },
      { label: "Musicien", emoji: "🎵" },
      { label: "DJ", emoji: "🎧" },
      { label: "Chanteur", emoji: "🎤" },
      { label: "Danseur / Chorégraphe", emoji: "💃" },
      { label: "Acteur / Comédien", emoji: "🎬" },
      { label: "Mannequin", emoji: "👠" },
      { label: "Écrivain", emoji: "✍️" },
      { label: "Créateur de contenu", emoji: "📹" },
      { label: "Décorateur d'intérieur", emoji: "🛋️" },
      { label: "Styliste de mode", emoji: "👗" },
    ],
  },
  {
    id: "sport_loisirs",
    label: "Sport & Loisirs",
    icone: "⚽",
    metiers: [
      { label: "Footballeur / Sportif professionnel", emoji: "⚽" },
      { label: "Entraîneur sportif", emoji: "🏋️" },
      { label: "Coach fitness", emoji: "💪" },
      { label: "Arbitre", emoji: "🟨" },
      { label: "Lutteur", emoji: "🤼" },
      { label: "Maître-nageur", emoji: "🏊" },
      { label: "Guide touristique", emoji: "🗺️" },
    ],
  },
  {
    id: "services",
    label: "Services",
    icone: "🤝",
    metiers: [
      { label: "Imam / Guide religieux", emoji: "🕌" },
      { label: "Travailleur social", emoji: "🤲" },
      { label: "Chef cuisinier", emoji: "👨‍🍳" },
      { label: "Restaurateur", emoji: "🍽️" },
      { label: "Serveur", emoji: "🍴" },
      { label: "Barman", emoji: "🍹" },
      { label: "Personnel hôtelier", emoji: "🏨" },
      { label: "Réceptionniste", emoji: "🛎️" },
      { label: "Steward / Hôtesse de l'air", emoji: "✈️" },
      { label: "Agent de voyage", emoji: "🧳" },
      { label: "Commerçant", emoji: "🏪" },
      { label: "Vendeur ambulant", emoji: "🛒" },
      { label: "Agent d'entretien / Femme de ménage", emoji: "🧹" },
      { label: "Blanchisseur", emoji: "🧺" },
      { label: "Nounou / Baby-sitter", emoji: "🍼" },
      { label: "Masseur", emoji: "💆" },
      { label: "Gardien / Vigile", emoji: "🔑" },
      { label: "Standardiste / Téléopérateur", emoji: "☎️" },
    ],
  },
];

/** Recherche insensible à la casse/aux accents sur le libellé du métier. */
export function rechercherMetiers(texte) {
  const q = (texte || "")
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
  if (!q) return CATEGORIES_METIERS;
  return CATEGORIES_METIERS.map((cat) => ({
    ...cat,
    metiers: cat.metiers.filter((m) =>
      m.label
        .toLowerCase()
        .normalize("NFD")
        .replace(/[̀-ͯ]/g, "")
        .includes(q)
    ),
  })).filter((cat) => cat.metiers.length > 0);
}
