export const SPONTANEOUS_COMPANIES = [
  // --- LISTES PRÉCÉDENTES (65 Entreprises) ---
  {
    id: "semi-sarl",
    slug: "semi-sarl",
    company: "SEMI SARL",
    title: "Candidature Spontanée - SEMI SARL",
    domains: "QHSE, Construction, Pôle Aquacole",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Opportunités de candidature spontanée au sein de SEMI SARL pour les métiers du QHSE, de la construction et du pôle aquacole.",
    rawContact: "sarrsoda@semisenegal.sn",
    contactType: "email",
    email: "sarrsoda@semisenegal.sn",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["QHSE", "Construction", "Pôle Aquacole"],
  },
  {
    id: "c2k-staffing",
    slug: "c2k-staffing",
    company: "C2K Staffing (Sabodala)",
    title: "Candidature Spontanée - C2K Staffing (Sabodala)",
    domains: "Mines, HSE, Logistique, Forage, Admin",
    location: "Sabodala, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "C2K Staffing recrute en candidature spontanée dans les secteurs des mines, HSE, logistique, forage et administration.",
    rawContact: "recrutement@c2kstaffing.com",
    contactType: "email",
    email: "recrutement@c2kstaffing.com",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Mines", "HSE", "Logistique", "Forage", "Administration"],
  },
  {
    id: "boad",
    slug: "boad",
    company: "BOAD",
    title: "Candidature Spontanée / Stages - BOAD",
    domains: "Audit, Data, Finance, IT, RH (Stages)",
    location: "Afrique de l'Ouest / Sénégal",
    contract_type: "Stages & Spontané",
    description: "Programme de stages et opportunités de carrières à la Banque Ouest Africaine de Développement (BOAD) en audit, data, finance, IT et RH.",
    rawContact: "jobs.boad.org/programme-de-stages-2026",
    contactType: "url",
    externalLink: "https://jobs.boad.org/programme-de-stages-2026",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Audit", "Data Science", "Finance", "IT", "Ressources Humaines"],
  },
  {
    id: "wave",
    slug: "wave",
    company: "Wave",
    title: "Candidature Spontanée / Stages - Wave",
    domains: "Achats, RH, Marketing, Finance (Stages)",
    location: "Dakar, Sénégal",
    contract_type: "Stages & Emplois",
    description: "Rejoignez Wave Mobile Money. Soumettez votre candidature pour nos opportunités en achats, RH, marketing et finance.",
    rawContact: "wave.com/careers/job/6097812004",
    contactType: "url",
    externalLink: "https://wave.com/careers/job/6097812004",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Achats", "RH", "Marketing", "Finance"],
  },
  {
    id: "societe-int-ingenierie-conseil",
    slug: "societe-int-ingenierie-conseil",
    company: "Société Int. d’Ingénierie Conseil",
    title: "Candidature Spontanée - Société Int. d’Ingénierie Conseil",
    domains: "Hydro-agronomie, Génie rural",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Société Internationale d'Ingénierie Conseil reçoit vos candidatures spontanées dans les domaines de l'hydro-agronomie et du génie rural.",
    rawContact: "recrute.societe.internationale@gmail.com",
    contactType: "email",
    email: "recrute.societe.internationale@gmail.com",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Hydro-agronomie", "Génie rural"],
  },
  {
    id: "tectra-senegal",
    slug: "tectra-senegal",
    company: "Tectra Sénégal",
    title: "Candidature Spontanée - Tectra Sénégal",
    domains: "Transport, Logistique, Permis C",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Tectra Sénégal recrute des profils qualifiés dans le transport, la logistique et les chauffeurs avec Permis C.",
    rawContact: "recrutement@tectra.sn",
    contactType: "email",
    email: "recrutement@tectra.sn",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Transport", "Logistique", "Conduite (Permis C)"],
  },
  {
    id: "cbao-attijariwafa-bank",
    slug: "cbao-attijariwafa-bank",
    company: "CBAO Attijariwafa Bank",
    title: "Candidature Spontanée - CBAO Attijariwafa Bank",
    domains: "IT, Full Stack, Data Science, Cybersécurité",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Déposez votre candidature spontanée auprès de la CBAO Attijariwafa Bank pour les postes en IT, développement Full Stack, Data Science et Cybersécurité.",
    rawContact: "K.abouyaala@attijariwafa.com",
    contactType: "email",
    email: "K.abouyaala@attijariwafa.com",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["IT", "Développement Full Stack", "Data Science", "Cybersécurité"],
  },
  {
    id: "canal-plus-senegal",
    slug: "canal-plus-senegal",
    company: "Canal+ Sénégal",
    title: "Candidature Spontanée - Canal+ Sénégal",
    domains: "Data Analysis, Anti-Piratage, Power BI",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Postulez aux opportunités chez Canal+ Sénégal en analyse de données, lutte anti-piratage et business intelligence (Power BI).",
    rawContact: "joinus.canalplus.com/job/Dakar-Chargé-Anti-piratage",
    contactType: "url",
    externalLink: "https://joinus.canalplus.com/job/Dakar-Chargé-Anti-piratage",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Data Analysis", "Anti-Piratage", "Power BI / BI"],
  },
  {
    id: "sama-hotel",
    slug: "sama-hotel",
    company: "Sama Hôtel",
    title: "Candidature Spontanée - Sama Hôtel",
    domains: "Hôtellerie, Support IT, Profil Bilingue",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Sama Hôtel recherche des talents dans l'hôtellerie, le support IT et des candidats aux profils bilingues.",
    rawContact: "info@samahotels.com",
    contactType: "email",
    email: "info@samahotels.com",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Hôtellerie", "Support IT", "Profils Bilingues"],
  },
  {
    id: "irritec-senegal",
    slug: "irritec-senegal",
    company: "Irritec Sénégal",
    title: "Candidature Spontanée - Irritec Sénégal",
    domains: "Irrigation, Agro-technique, Commercial",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Rejoignez Irritec Sénégal et apportez vos compétences en irrigation, solutions agro-techniques et commercialisation.",
    rawContact: "irritec.com/careers",
    contactType: "url",
    externalLink: "https://irritec.com/careers",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Irrigation", "Agro-technique", "Commercial"],
  },
  {
    id: "pullman-dakar-teranga",
    slug: "pullman-dakar-teranga",
    company: "Pullman Dakar Teranga",
    title: "Candidature Spontanée - Pullman Dakar Teranga",
    domains: "Hôtellerie de luxe, Restauration",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Intégrez les équipes du Pullman Dakar Teranga (Groupe Accor) dans l'hôtellerie de luxe et la restauration de haut standing.",
    rawContact: "careers.accor.com",
    contactType: "url",
    externalLink: "https://careers.accor.com",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Hôtellerie de luxe", "Restauration", "Service Client"],
  },
  {
    id: "oryx-energies",
    slug: "oryx-energies",
    company: "Oryx Energies",
    title: "Candidature Spontanée - Oryx Energies",
    domains: "Pétrole, Logistique, Opérations",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Oryx Energies accueille les candidatures spontanées dans le secteur pétrolier, la logistique industrielle et la gestion des opérations.",
    rawContact: "oryxenergies.com/careers",
    contactType: "url",
    externalLink: "https://oryxenergies.com/careers",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Pétrole & Énergie", "Logistique", "Opérations"],
  },
  {
    id: "coris-bank-international",
    slug: "coris-bank-international",
    company: "Coris Bank International",
    title: "Candidature Spontanée - Coris Bank International",
    domains: "Banque, Finance, Clientèle",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Rejoignez Coris Bank International et développez votre carrière dans le secteur bancaire, la finance et la relation clientèle.",
    rawContact: "coris-bank.com/carrieres",
    contactType: "url",
    externalLink: "https://coris-bank.com/carrieres",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Banque", "Finance", "Gestion de Clientèle"],
  },
  {
    id: "saveurs-d-asie",
    slug: "saveurs-d-asie",
    company: "Saveurs d’Asie",
    title: "Candidature Spontanée - Saveurs d’Asie",
    domains: "Restauration, Cuisine, Service",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Saveurs d'Asie recrute en candidature spontanée dans les domaines de la restauration, la cuisine et le service en salle.",
    rawContact: "contact@saveursdasie.sn",
    contactType: "email",
    email: "contact@saveursdasie.sn",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Restauration", "Cuisine", "Service"],
  },
  {
    id: "grand-bleu-sa",
    slug: "grand-bleu-sa",
    company: "GRAND BLEU S.A",
    title: "Candidature Spontanée - GRAND BLEU S.A",
    domains: "Pêche industrielle, Logistique",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "GRAND BLEU S.A reçoit les candidatures spontanées pour la pêche industrielle, la gestion maritime et la logistique.",
    rawContact: "recrutement@grandbleu.sn",
    contactType: "email",
    email: "recrutement@grandbleu.sn",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Pêche industrielle", "Logistique maritime"],
  },
  {
    id: "axil-hotels",
    slug: "axil-hotels",
    company: "Axil Hotels",
    title: "Candidature Spontanée - Axil Hotels",
    domains: "Hôtellerie, Accueil, Maintenance",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Axil Hotels recherche des profils dynamiques en hôtellerie, accueil & réception ainsi qu'en maintenance technique.",
    rawContact: "rh@axilhotels.com",
    contactType: "email",
    email: "rh@axilhotels.com",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Hôtellerie", "Accueil", "Maintenance"],
  },
  {
    id: "laiterie-du-berger",
    slug: "laiterie-du-berger",
    company: "Laiterie du Berger",
    title: "Candidature Spontanée - Laiterie du Berger",
    domains: "Agroalimentaire, Distribution",
    location: "Richard-Toll / Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "La Laiterie du Berger recrute pour soutenir la production agroalimentaire locale et le réseau de distribution.",
    rawContact: "recrutement@laiterieduberger.com",
    contactType: "email",
    email: "recrutement@laiterieduberger.com",
    documentsRequired: "CV & Lettre de motivation",
    image_url: null,
    poles: ["Agroalimentaire", "Distribution", "Production locale"],
  },
  {
    id: "seter-spontanee",
    slug: "seter",
    company: "SETER",
    title: "Candidature Spontanée - SETER",
    domains: "RH, Transport, Achats, Com, Marketing, Maintenance, Finance, QHSE, Sûreté, SI, Conducteurs, Juridique, Exploitation",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Rejoignez la SETER et participez au développement du Train Express Régional !",
    rawContact: "seter.sn",
    contactType: "url",
    externalLink: "https://seter.sn/recrutement/",
    documentsRequired: "CV, Lettre de motivation",
    image_url: "/seterimage.avif",
    poles: ["RH", "Transport", "Achats", "Marketing", "Maintenance", "Finance", "QHSE"],
  },
  {
    id: "soboa-spontanee",
    slug: "soboa",
    company: "SOBOA",
    title: "Candidature Spontanée - SOBOA",
    domains: "Stage Académique, Stage Pro, Intérim, CDD, CDI",
    location: "Dakar, Sénégal",
    contract_type: "Stage, Intérim, CDD, CDI",
    description: "La Société des Brasseries de l'Ouest-Africain (SOBOA) recherche des talents.",
    rawContact: "soboa.sn/carriere",
    contactType: "url",
    externalLink: "https://soboa.sn/carriere/",
    documentsRequired: "CV, Lettre de motivation",
    image_url: "/soboa.png",
    poles: ["Production", "Qualité", "Maintenance", "Logistique"],
  },
  {
    id: "dakardemdikk-spontanee",
    slug: "dakar-dem-dikk",
    company: "Dakar Dem Dikk",
    title: "Candidature Spontanée - Dakar Dem Dikk",
    domains: "Conducteur, Receveur, Contrôleur, IT, RH, Finance, Marketing, Commercial, Com, BTP, Secrétariat",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Rejoignez Dakar Dem Dikk pour les métiers du transport, de l'IT et des services.",
    rawContact: "jobs.demdikk.sn",
    contactType: "url",
    externalLink: "https://jobs.demdikk.sn/offres/candidature-spontanee/",
    documentsRequired: "CV, Lettre de motivation",
    image_url: "/demdikk.jpeg",
    poles: ["Conducteur", "Receveur", "IT", "RH", "Finance"],
  },
  {
    id: "supeco-senegal",
    slug: "supeco-senegal",
    company: "SUPECO Sénégal",
    title: "Candidature Spontanée - SUPECO Sénégal",
    domains: "Libre-service, Rayonistes, Caissiers, Chefs de secteur, Supermarché",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "SUPECO Sénégal recrute des profils en grande distribution.",
    rawContact: "supeco.net/recrutement",
    contactType: "url",
    externalLink: "https://supeco.net/recrutement",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Libre-service", "Caissiers", "Rayonistes"],
  },
  {
    id: "ansd",
    slug: "ansd",
    company: "ANSD",
    title: "Candidature Spontanée - ANSD",
    domains: "Géomaticiens, Statisticiens chargés d’études, Assistants géomatique",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "L'Agence Nationale de la Statistique et de la Démographie (ANSD) recrute.",
    rawContact: "recrute.ansd.sn",
    contactType: "url",
    externalLink: "https://recrute.ansd.sn",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Géomatique", "Statistique"],
  },
  {
    id: "sococim-industries",
    slug: "sococim-industries",
    company: "SOCOCIM Industries",
    title: "Candidature Spontanée - SOCOCIM Industries",
    domains: "Tous domaines (Candidature spontanée)",
    location: "Rufisque / Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "SOCOCIM Industries reçoit les candidatures spontanées.",
    rawContact: "sococim.com/candidature-spontanee",
    contactType: "url",
    externalLink: "https://sococim.com/candidature-spontanee",
    documentsRequired: "CV, Lettre de motivation (Max 50 Mo)",
    image_url: null,
    poles: ["Production", "Maintenance", "QHSE"],
  },
  {
    id: "intelcia-senegal",
    slug: "intelcia-senegal",
    company: "Intelcia Sénégal",
    title: "Candidature Spontanée - Intelcia Sénégal",
    domains: "Conseillers centre de contact, Superviseurs, Back Office, IT, RH, Ventes",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Intelcia Sénégal recrute des conseillers client et techniciens IT/RH.",
    rawContact: "careers.intelcia.com",
    contactType: "url",
    externalLink: "https://careers.intelcia.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Centre de contact", "Supervision", "Ventes"],
  },
  {
    id: "nestle",
    slug: "nestle",
    company: "Nestlé",
    title: "Candidature Spontanée - Nestlé",
    domains: "Achats, Ventes, Admin, Audit, Finance, RH, Production, IT, QHSE",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Postulez auprès de Nestlé Sénégal dans les domaines divers.",
    rawContact: "jobdetails.nestle.com",
    contactType: "url",
    externalLink: "https://jobdetails.nestle.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Achats", "Ventes", "QHSE", "Production"],
  },
  {
    id: "senico",
    slug: "senico",
    company: "SENICO",
    title: "Candidature Spontanée - SENICO",
    domains: "Production, Maintenance industrielle, Logistique, Qualité, Admin",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "SENICO reçoit vos candidatures spontanées.",
    rawContact: "recrute@senico.sn",
    contactType: "email",
    email: "recrute@senico.sn",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Production", "Maintenance", "Qualité"],
  },
  {
    id: "groupe-kirene",
    slug: "groupe-kirene",
    company: "Groupe Kirène",
    title: "Candidature Spontanée - Groupe Kirène",
    domains: "Production, Maintenance, Qualité, Logistique, Vente, Finance, RH, Stocks",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Rejoignez le Groupe Kirène.",
    rawContact: "kirene-groupe.com/carriere",
    contactType: "url",
    externalLink: "https://kirene-groupe.com/carriere",
    documentsRequired: "CV, Lettre de motivation, Diplômes, Attestations",
    image_url: null,
    poles: ["Production", "Qualité", "Logistique", "Vente"],
  },
  {
    id: "sgfp",
    slug: "sgfp",
    company: "SGFP",
    title: "Candidature Spontanée - SGFP",
    domains: "Pompistes",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "SGFP recrute des pompistes. Contact : 77 791 72 19 / 77 136 29 29.",
    rawContact: "cm@sgf.sn",
    contactType: "email",
    email: "cm@sgf.sn",
    documentsRequired: "CV, LM, CNI légalisée, Extrait de naissance, Casier judiciaire, Certificat médical",
    image_url: null,
    poles: ["Pompistes", "Services station"],
  },
  {
    id: "djolof-chicken-edk",
    slug: "djolof-chicken-edk",
    company: "Djolof Chicken (EDK)",
    title: "Candidature Spontanée - Djolof Chicken (EDK)",
    domains: "Caissiers, Serveurs, Vendeurs, Équipiers, Cuisiniers, Admin",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Djolof Chicken recrute du personnel de restauration.",
    rawContact: "info@edkoil.com",
    contactType: "email",
    email: "info@edkoil.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Cuisine", "Service", "Caisse"],
  },
  {
    id: "sedima-sa",
    slug: "sedima-sa",
    company: "SEDIMA SA",
    title: "Candidature Spontanée - SEDIMA SA",
    domains: "Agronomes/Vétérinaires, Agroalimentaire, Marketing, Logistique, Finance, RH",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "SEDIMA SA accueille les candidats en agronomie et agroalimentaire.",
    rawContact: "sedima.com/nouvelle-page",
    contactType: "url",
    externalLink: "https://sedima.com/nouvelle-page",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Agronomie", "Vétérinaire", "Agroalimentaire"],
  },
  {
    id: "groupe-sonatel",
    slug: "groupe-sonatel",
    company: "Groupe Sonatel",
    title: "Candidature Spontanée - Groupe Sonatel",
    domains: "IT, Télécoms, Marketing, Finance, Gestion de projet, Data, Digital",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Déposez votre candidature au Groupe Sonatel.",
    rawContact: "sonatel.sn/demande-demplois",
    contactType: "url",
    externalLink: "https://sonatel.sn/demande-demplois",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["IT & Télécoms", "Data & Digital", "Marketing"],
  },
  {
    id: "uniparco-senegal",
    slug: "uniparco-senegal",
    company: "UNIPARCO Sénégal",
    title: "Candidature Spontanée - UNIPARCO Sénégal",
    domains: "Employés journaliers, Agents permanents (Production, Logistique)",
    location: "Usine Colobane, Dakar, Sénégal",
    contract_type: "Journalier & Permanent",
    description: "UNIPARCO Sénégal recrute journaliers et permanents.",
    rawContact: "uniparco.sn@gmail.com",
    contactType: "email",
    email: "uniparco.sn@gmail.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Production", "Logistique"],
  },
  {
    id: "eiffage-senegal",
    slug: "eiffage-senegal",
    company: "Eiffage Sénégal",
    title: "Candidature Spontanée - Eiffage Sénégal",
    domains: "Ingénieurs, Techniciens, Chefs de projet, Génie civil, Électricité, BTP",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Eiffage Sénégal recrute en BTP et génie civil.",
    rawContact: "eiffage.sn/home/contact.html",
    contactType: "url",
    externalLink: "https://eiffage.sn/home/contact.html",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Génie Civil", "BTP", "Électricité"],
  },
  {
    id: "autoroutes-du-senegal",
    slug: "autoroutes-du-senegal",
    company: "Autoroutes du Sénégal",
    title: "Candidature Spontanée - Autoroutes du Sénégal",
    domains: "Exploitation autoroutière, Génie civil, Maintenance, Transport, Support",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Postulez aux emplois de l'exploitation autoroutière.",
    rawContact: "autoroutesdusenegal.sn",
    contactType: "url",
    externalLink: "https://autoroutesdusenegal.sn",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Exploitation autoroutière", "Maintenance"],
  },
  {
    id: "yas-senegal-axian",
    slug: "yas-senegal-axian",
    company: "Yas Sénégal (Axian)",
    title: "Candidature Spontanée - Yas Sénégal (Axian)",
    domains: "Portfolio Manager, Manager QHSE, Product Owner, Digital Growth, Media",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Yas Sénégal / Axian Group recrute des managers.",
    rawContact: "axian-group.csod.com",
    contactType: "url",
    externalLink: "https://axian-group.csod.com",
    documentsRequired: "CV, Lettre de motivation, Pièces diverses",
    image_url: null,
    poles: ["Product Owner", "QHSE", "Digital Growth"],
  },
  {
    id: "kpay-senegal",
    slug: "kpay-senegal",
    company: "Kpay Sénégal",
    title: "Candidature Spontanée - Kpay Sénégal",
    domains: "Infographe (Design graphique, branding, cartes PVC, visuels)",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Kpay Sénégal recherche des infographes.",
    rawContact: "recrutement@quickpay.sn",
    contactType: "email",
    email: "recrutement@quickpay.sn",
    documentsRequired: "CV, Portfolio (Obligatoire)",
    image_url: null,
    poles: ["Infographie", "Design Graphique"],
  },
  {
    id: "sunu-assurances-vie",
    slug: "sunu-assurances-vie",
    company: "SUNU Assurances Vie",
    title: "Candidature Spontanée - SUNU Assurances Vie",
    domains: "Conseillers en Assurance Vie / Conseillers Commerciaux",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "SUNU Assurances Vie recrute des conseillers.",
    rawContact: "directioncommerciale.senegal@sunu-group.com",
    contactType: "email",
    email: "directioncommerciale.senegal@sunu-group.com",
    documentsRequired: "CV, Lettre de motivation (Objet: Conseiller Commercial)",
    image_url: null,
    poles: ["Assurance Vie", "Vente"],
  },
  {
    id: "port-autonome-de-dakar",
    slug: "port-autonome-de-dakar",
    company: "Port Autonome de Dakar",
    title: "Candidature Spontanée - Port Autonome de Dakar",
    domains: "Exploitation portuaire, Logistique, Génie civil, Manutention, Sûreté",
    location: "Port de Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Port Autonome de Dakar recrute.",
    rawContact: "portdakar.sn/candidature-spontanee",
    contactType: "url",
    externalLink: "https://portdakar.sn/candidature-spontanee",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Exploitation portuaire", "Logistique"],
  },
  {
    id: "china-mall-dakar",
    slug: "china-mall-dakar",
    company: "China Mall Dakar",
    title: "Candidature Spontanée - China Mall Dakar",
    domains: "Commerce, Grande distribution, Vente, Caisse, Rayon, Logistique",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "China Mall Dakar recrute pour la grande distribution.",
    rawContact: "info@chinamalldakar.com",
    contactType: "email",
    email: "info@chinamalldakar.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Vente", "Caisse", "Logistique"],
  },
  {
    id: "american-bazar",
    slug: "american-bazar",
    company: "American Bazar",
    title: "Candidature Spontanée - American Bazar",
    domains: "Commerciales (Accueil, conseil et vente)",
    location: "Sipress / Liberté 6, Dakar",
    contract_type: "Dépôt physique & Contact",
    description: "American Bazar recrute des commerciales.",
    rawContact: "Contacts : +221 77 103 63 63 / +221 77 174 62 62",
    contactType: "email",
    email: "contact@americanbazar.sn",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Accueil", "Vente"],
  },
  {
    id: "auchan-senegal",
    slug: "auchan-senegal",
    company: "Auchan Sénégal",
    title: "Candidature Spontanée - Auchan Sénégal",
    domains: "Caissiers, Libre-service, Logistique, Chefs de rayon, Sécurité, Entretien",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Auchan Sénégal recrute via SociumJob.",
    rawContact: "sociumjob.com",
    contactType: "url",
    externalLink: "https://sociumjob.com",
    documentsRequired: "Profil candidat / CV en ligne",
    image_url: null,
    poles: ["Caisse", "Libre-service", "Sécurité"],
  },
  {
    id: "md-holding",
    slug: "md-holding",
    company: "MD HOLDING",
    title: "Candidature Spontanée - MD HOLDING",
    domains: "Électriciens, Conducteurs travaux, Peintres, Soudeurs, Chauffeurs, Comptables, QHSE",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "MD HOLDING recrute des techniciens du bâtiment.",
    rawContact: "yacine.mdholdingci@gmail.com",
    contactType: "email",
    email: "yacine.mdholdingci@gmail.com",
    documentsRequired: "CV, Copies légalisées des diplômes",
    image_url: null,
    poles: ["Électricité", "Chauffeur", "Comptabilité"],
  },
  {
    id: "aibd-humanis",
    slug: "aibd-humanis",
    company: "AIBD / Humanis",
    title: "Candidature Spontanée - AIBD / Humanis",
    domains: "Hôtesses d’accueil événementielles",
    location: "AIBD / Diass, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Humanis recrute des hôtesses d'accueil pour l'AIBD.",
    rawContact: "recrutement@humanis-sn.com",
    contactType: "email",
    email: "recrutement@humanis-sn.com",
    documentsRequired: "CV",
    image_url: null,
    poles: ["Hôtesses AIBD", "Accueil"],
  },
  {
    id: "paps-senegal",
    slug: "paps-senegal",
    company: "Paps Sénégal",
    title: "Candidature Spontanée - Paps Sénégal",
    domains: "Téléopérateur(trice)",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Paps Sénégal recrute des téléopérateurs.",
    rawContact: "jobs@paps-app.com",
    contactType: "email",
    email: "jobs@paps-app.com",
    documentsRequired: "CV (Objet: Candidature – TÉLÉOPÉRATEUR)",
    image_url: null,
    poles: ["Téléopération", "Relation Client"],
  },
  {
    id: "edk-oil",
    slug: "edk-oil",
    company: "EDK OIL",
    title: "Candidature Spontanée - EDK OIL",
    domains: "Trésorerie, Comptabilité, Achats, Pricing, Finance",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "EDK OIL recrute en finance et comptabilité.",
    rawContact: "recrutement.lowprice@edkoil.com",
    contactType: "email",
    email: "recrutement.lowprice@edkoil.com",
    documentsRequired: "CV, Lettre de motivation (Profil précisé en objet)",
    image_url: null,
    poles: ["Trésorerie", "Comptabilité", "Achats"],
  },
  {
    id: "hotel-terrou-bi",
    slug: "hotel-terrou-bi",
    company: "Hôtel Terrou-Bi",
    title: "Candidature Spontanée - Hôtel Terrou-Bi",
    domains: "Réceptionnistes, Hôtellerie, Restauration, Tourisme",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Terrou-Bi recrute des réceptionnistes et du personnel de service.",
    rawContact: "recrutement@terroubi.com",
    contactType: "email",
    email: "recrutement@terroubi.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Réception", "Hôtellerie", "Restauration"],
  },
  {
    id: "seneau",
    slug: "seneau",
    company: "SEN'EAU",
    title: "Candidature Spontanée - SEN'EAU",
    domains: "Hydraulique, Traitement de l'eau, Service Client",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "SEN'EAU recrute en candidature spontanée.",
    rawContact: "recrutement@seneau.sn",
    contactType: "email",
    email: "recrutement@seneau.sn",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Hydraulique", "Traitement de l'eau", "Service Client"],
  },
  {
    id: "free-senegal",
    slug: "free-senegal",
    company: "Free Sénégal",
    title: "Candidature Spontanée - Free Sénégal",
    domains: "Télécoms, IT, Vente, Service Client",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Free Sénégal recrute en télécoms et IT.",
    rawContact: "recrutement@free.sn",
    contactType: "email",
    email: "recrutement@free.sn",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Télécoms", "IT", "Vente"],
  },
  {
    id: "dp-world-dakar",
    slug: "dp-world-dakar",
    company: "DP World Dakar",
    title: "Candidature Spontanée - DP World Dakar",
    domains: "Logistique, Manutention portuaire, Douane",
    location: "Port de Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "DP World Dakar recrute pour la logistique maritime.",
    rawContact: "recrute.dakar@dpworld.com",
    contactType: "email",
    email: "recrute.dakar@dpworld.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Logistique", "Manutention portuaire", "Douane"],
  },
  {
    id: "societe-generale-senegal",
    slug: "societe-generale-senegal",
    company: "Société Générale Sénégal (SGSN)",
    title: "Candidature Spontanée - Société Générale Sénégal (SGSN)",
    domains: "Banque, Finance, Audit, Conformité",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Société Générale Sénégal (SGSN) recrute en banque et finance.",
    rawContact: "recrutement.sgsn@socgen.com",
    contactType: "email",
    email: "recrutement.sgsn@socgen.com",
    documentsRequired: "CV, Diplômes",
    image_url: null,
    poles: ["Banque", "Finance", "Audit"],
  },
  {
    id: "senelec",
    slug: "senelec",
    company: "Senelec",
    title: "Candidature Spontanée - Senelec",
    domains: "Électricité, Maintenance industrielle, Ingénierie",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "La Senelec recrute des techniciens et ingénieurs.",
    rawContact: "candidature@senelec.sn",
    contactType: "email",
    email: "candidature@senelec.sn",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Électricité", "Maintenance industrielle"],
  },
  {
    id: "apix",
    slug: "apix",
    company: "APIX",
    title: "Candidature Spontanée - APIX",
    domains: "Administration, Promotion des investissements",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "L'APIX recrute en administration et promotion des investissements.",
    rawContact: "apix@apix.sn",
    contactType: "email",
    email: "apix@apix.sn",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Administration", "Promotion des investissements"],
  },
  {
    id: "baobab-senegal",
    slug: "baobab-senegal",
    company: "Baobab Sénégal",
    title: "Candidature Spontanée - Baobab Sénégal",
    domains: "Microfinance, Crédit, Audit, Caisse",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Baobab Sénégal recrute en microfinance.",
    rawContact: "recrutement.sn@baobab.com",
    contactType: "email",
    email: "recrutement.sn@baobab.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Microfinance", "Crédit", "Caisse"],
  },
  {
    id: "sonacos",
    slug: "sonacos",
    company: "Sonacos",
    title: "Candidature Spontanée - Sonacos",
    domains: "Agro-industrie, Logistique, Production",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Sonacos recrute des profils en agro-industrie.",
    rawContact: "contact@sonacos.sn",
    contactType: "email",
    email: "contact@sonacos.sn",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Agro-industrie", "Logistique", "Production"],
  },
  {
    id: "bicis",
    slug: "bicis",
    company: "BICIS",
    title: "Candidature Spontanée - BICIS",
    domains: "Banque de réseau, Guichet, Finance",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "La BICIS recrute pour la banque de réseau.",
    rawContact: "recrutement@bicis.sn",
    contactType: "email",
    email: "recrutement@bicis.sn",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Banque de réseau", "Guichet"],
  },
  {
    id: "cgf-bourse",
    slug: "cgf-bourse",
    company: "CGF Bourse",
    title: "Candidature Spontanée - CGF Bourse",
    domains: "Finance de marché, Bourse, Analyse financière",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "CGF Bourse recrute en finance de marché.",
    rawContact: "recrutement@cgfbourse.com",
    contactType: "email",
    email: "recrutement@cgfbourse.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Finance de marché", "Bourse"],
  },
  {
    id: "cstt-ao",
    slug: "cstt-ao",
    company: "CSTT-AO",
    title: "Candidature Spontanée - CSTT-AO",
    domains: "Transit, Transport logistique, Manutention",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "CSTT-AO recrute en transit et transport logistique.",
    rawContact: "recrutement@csttao.com",
    contactType: "email",
    email: "recrutement@csttao.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Transit", "Transport logistique"],
  },
  {
    id: "majorel-senegal-teleperformance",
    slug: "majorel-senegal-teleperformance",
    company: "Majorel Sénégal (Teleperformance)",
    title: "Candidature Spontanée - Majorel Sénégal (Teleperformance)",
    domains: "Centre d'appels, Téléconseillers, Support",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Majorel / Teleperformance recrute des téléconseillers.",
    rawContact: "recrutement.senegal@teleperformance.com",
    contactType: "email",
    email: "recrutement.senegal@teleperformance.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Centre d'appels", "Téléconseillers"],
  },
  {
    id: "air-senegal",
    slug: "air-senegal",
    company: "Air Sénégal",
    title: "Candidature Spontanée - Air Sénégal",
    domains: "Aéronautique, Personnel navigant, Logistique, Commercial, Fonctions support",
    location: "Dakar / AIBD, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Rejoignez la compagnie nationale Air Sénégal. Postulez en candidature spontanée pour le personnel navigant, la logistique aéronautique, le commercial et les fonctions support.",
    rawContact: "recrutement@airsenegal.sn",
    contactType: "email",
    email: "recrutement@airsenegal.sn",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Aéronautique", "Personnel navigant", "Logistique", "Commercial", "Fonctions support"],
  },
  {
    id: "sivop-senegal",
    slug: "sivop-senegal",
    company: "SIVOP SÉNÉGAL (SOCIÉTÉ IVOIRIENNE DE PARFUMERIE DU SÉNÉGAL)",
    title: "Candidature Spontanée & Dépôt Physique - SIVOP SÉNÉGAL",
    domains: "Produits cosmétiques, Parfumerie, Soins du corps",
    location: "Autoroute prolongée, en face de SDE Pikine, BP 3313, Dakar - Sénégal",
    contract_type: "Dépôt physique & Spontané",
    description: "SIVOP SÉNÉGAL (Société Ivoirienne de Parfumerie du Sénégal) recrute en candidature spontanée et dépôt de dossier sur place. Adresse : Autoroute prolongée, en face de SDE Pikine, BP 3313, Dakar. Tél: (+221) 33 879 85 85 / Fax: (+221) 33 854 64 00.",
    rawContact: "www.sivop.com | Tél: (+221) 33 879 85 85",
    contactType: "url",
    externalLink: "https://www.sivop.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Produits cosmétiques", "Parfumerie", "Soins du corps", "Recrutement sur place"],
  },
  {
    id: "isc-talentapro",
    slug: "isc-talentapro",
    company: "ISC / International Staffing Company",
    title: "Candidature Spontanée - ISC (International Staffing Company)",
    domains: "Laveur, Pompiste, Caissier, Chef de piste, Gérant, Gérant boutique",
    location: "Dakar, Sénégal",
    contract_type: "Intérim & Placement",
    description: "L'International Staffing Company (ISC) recrute des profils d'exploitation de stations-services : laveurs, pompistes, caissiers, chefs de piste, gérants et gérants de boutique.",
    rawContact: "ischcrecruitment@groupetalentapro.com",
    contactType: "email",
    email: "ischcrecruitment@groupetalentapro.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Laveur", "Pompiste", "Caissier", "Chef de piste", "Gérant station", "Gérant boutique"],
  },
  {
    id: "isc-direction",
    slug: "isc-direction",
    company: "International Staffing Company (Direction)",
    title: "Inscription Vivier Intérim - ISC Direction",
    domains: "Relance / Inscription au vivier intérim (Tous secteurs)",
    location: "Dakar, Sénégal",
    contract_type: "Vivier Intérim & Relance",
    description: "Inscrivez-vous directement au vivier général de l'International Staffing Company (ISC) pour être recontacté sur des opportunités en intérim et placement permanent.",
    rawContact: "manager@istaffingcompany.net",
    contactType: "email",
    email: "manager@istaffingcompany.net",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Vivier Intérim", "Placement Permanent", "Relance candidature"],
  },
  {
    id: "elton-oil-company",
    slug: "elton-oil-company",
    company: "ELTON Oil Company",
    title: "Candidature Spontanée - ELTON Oil Company",
    domains: "Tous postes réseau et siège (Exploitation, Service client, Admin)",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "ELTON Oil Company recrute pour l'ensemble de ses postes en réseau de stations et au siège social.",
    rawContact: "recrute@elton.sn",
    contactType: "email",
    email: "recrute@elton.sn",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Réseau stations", "Siège social", "Exploitation pétrolière"],
  },
  {
    id: "elton-oil-general",
    slug: "elton-oil-general",
    company: "ELTON Oil (Général)",
    title: "Candidature Spontanée - ELTON Oil (Contact Général)",
    domains: "Candidature spontanée globale",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Adresse de contact général pour l'envoi de dossiers de candidature spontanée auprès du Groupe ELTON Oil.",
    rawContact: "contact@eltonoil.com",
    contactType: "email",
    email: "contact@eltonoil.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Pétrole & Distribution", "Services généraux"],
  },
  {
    id: "star-oil-senegal",
    slug: "star-oil-senegal",
    company: "Star Oil Sénégal",
    title: "Candidature Spontanée - Star Oil Sénégal",
    domains: "Réseau stations et siège (Exploitation, Vente, Commercial, Support)",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Star Oil Sénégal reçoit les candidatures spontanées pour les métiers du réseau de stations-services et des directions du siège.",
    rawContact: "senegal@staroilgroup.com",
    contactType: "email",
    email: "senegal@staroilgroup.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Réseau stations", "Siège", "Commercial & Vente"],
  },
  {
    id: "totalenergies-marketing-senegal",
    slug: "totalenergies-marketing-senegal",
    company: "TotalEnergies Marketing Sénégal",
    title: "Candidature Spontanée - TotalEnergies Marketing Sénégal",
    domains: "Postes opérationnels et station (En complément du dépôt physique en station)",
    location: "Dakar & Réseau Sénégal",
    contract_type: "Candidature Spontanée (Email & Dépôt sur place)",
    description: "Adresse RH pour candidatures opérationnelles TotalEnergies Marketing Sénégal (à utiliser en complément du dépôt direct en station).",
    rawContact: "rh@total.sn",
    contactType: "email",
    email: "rh@total.sn",
    documentsRequired: "CV, Lettre de motivation (Complément dépôt en station)",
    image_url: null,
    poles: ["Opérationnel station", "Distribution énergie", "Service client station"],
  },

  // --- NOUVELLE LISTE MAJEURE (12 ENTREPRISES TRANS&ÉNERGIE) ---
  {
    id: "brt-dakar-mobilite",
    slug: "brt-dakar-mobilite",
    company: "BRT (Dakar Mobilité SA)",
    title: "Candidature Spontanée - BRT (Dakar Mobilité SA)",
    domains: "Marketing et Communication, Agent de vente, QHSE, Logistique, Informatique, Contrôle, Conduite (chauffeurs), Électricité, Mécanique, RH, Finance et Comptabilité, Administration",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Dakar Mobilité SA recrute pour le réseau BRT : conducteurs de bus, contrôleurs, agents de vente, mécaniciens, ingénieurs électricité/IT, RH et comptables.",
    rawContact: "sunubrt.sn/candidature",
    contactType: "url",
    externalLink: "https://sunubrt.sn/candidature",
    documentsRequired: "CV à jour, Lettre de motivation (précisant le domaine)",
    image_url: null,
    poles: ["Conduite", "Agents de vente", "Contrôle", "Mécanique & Électricité", "QHSE", "Logistique & IT"],
  },
  {
    id: "nabadji-call-center",
    slug: "nabadji-call-center",
    company: "Nabadji Call Center",
    title: "Candidature Spontanée - Nabadji Call Center",
    domains: "Centre d'appels (Téléconseillers, Vente / Service client)",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Nabadji Call Center recrute des téléconseillers et des télévendeurs pour ses activités de relation client.",
    rawContact: "recrutement@nabadji.com",
    contactType: "email",
    email: "recrutement@nabadji.com",
    documentsRequired: "CV à jour",
    image_url: null,
    poles: ["Centre d'appels", "Téléconseillers", "Vente & Service client"],
  },
  {
    id: "shell-senegal-vivo-energy",
    slug: "shell-senegal-vivo-energy",
    company: "Shell Sénégal (Vivo Energy Sénégal)",
    title: "Candidature Spontanée - Shell Sénégal (Vivo Energy)",
    domains: "Mines, Aviation, Marine, Agriculture, Construction, Transport, Industrie, Énergie",
    location: "Route des Hydrocarbures, Bel Air, BP 144, Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Vivo Energy Sénégal (Licencié Shell) recrute dans les secteurs minier, aéronautique, maritime, industriel et transport. Tél: +221 33 849 37 37 / +221 33 832 32 17.",
    rawContact: "vivoenergy.senegal@vivoenergy.com / Service-Client-Senegal@vivoenergy.com",
    contactType: "email",
    email: "vivoenergy.senegal@vivoenergy.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Mines & Aviation", "Marine & Transport", "Industrie & Énergie"],
  },
  {
    id: "ola-energy-senegal",
    slug: "ola-energy-senegal",
    company: "OLA Energy",
    title: "Candidature Spontanée - OLA Energy",
    domains: "Ingénierie, Durabilité, Transformation numérique, Aviation, RH, IT, Ventes, Logistique, Réseau de stations",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "OLA Energy recrute en ligne pour l'ensemble de ses métiers : ingénierie, réseau de stations, IT, logistique, RH et finance.",
    rawContact: "olaenergy.com/careers",
    contactType: "url",
    externalLink: "https://olaenergy.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Ingénierie & IT", "Réseau de stations", "Ventes & Logistique", "RH & Finance"],
  },
  {
    id: "star-oil-group",
    slug: "star-oil-group",
    company: "Star Oil",
    title: "Candidature Spontanée - Star Oil",
    domains: "Ingénierie, Transformation numérique, Aviation, RH, Ventes, Logistique, Réseau de stations, SSHE",
    location: "Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Star Oil recrute pour son réseau de distribution, la logistique pétrolière, la durabilité et l'exploitation des stations.",
    rawContact: "staroilgroup.com/form/contact",
    contactType: "url",
    externalLink: "https://staroilgroup.com/form/contact",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Réseau de stations", "Ingénierie & SSHE", "Ventes & Logistique"],
  },
  {
    id: "edk-group",
    slug: "edk-group",
    company: "EDK Group",
    title: "Candidature Spontanée - EDK Group",
    domains: "Toutes filiales / Multi-secteurs (Stations, Restauration, Retail, Finance)",
    location: "78M, Cité des Magistrats, CICES Foire, Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "EDK Group recrute dans toutes ses filiales (stations EDK, Djolof Chicken, Low Price). Tél: (+221) 33 820 73 02.",
    rawContact: "info@edkoil.com | Tél: (+221) 33 820 73 02",
    contactType: "email",
    email: "info@edkoil.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Multi-secteurs", "Stations EDK", "Restauration & Retail"],
  },
  {
    id: "sar-raffinage",
    slug: "sar-raffinage",
    company: "SAR (Société Africaine de Raffinage)",
    title: "Candidature Spontanée - SAR (Société Africaine de Raffinage)",
    domains: "Comptable, Transformation Numérique & SAP, Analyste SOC, Chimiste, Communication, Mécanicien, Instrumentiste, Stages",
    location: "Mbao / Dakar, Sénégal",
    contract_type: "Candidature Spontanée & Stages",
    description: "La Société Africaine de Raffinage (SAR) recrute des chimistes, instrumentistes, mécaniciens, comptables et ingénieurs IT. Tél: (221) 33 839 84 39 / Numéro vert: 800 00 34 34.",
    rawContact: "sar.sn/entreprise/deposez-votre-candidature-ici",
    contactType: "url",
    externalLink: "https://sar.sn/entreprise/deposez-votre-candidature-ici",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Raffinage", "Chimie & Laboratoire", "Mécanique & Instrumentiste", "IT & SAP"],
  },
  {
    id: "puma-energy-senegal",
    slug: "puma-energy-senegal",
    company: "Puma Energy Sénégal",
    title: "Candidature Spontanée - Puma Energy Sénégal",
    domains: "Lubrifiants, Vente au détail, Carburants commerciaux, Énergie propre, Aviation",
    location: "Immeuble Thiargane VDN, Rond Point Place OVMS, 3ème étage, Dakar",
    contract_type: "Candidature Spontanée",
    description: "Puma Energy Sénégal recrute dans la distribution de carburants, lubrifiants, énergies propres et aviation. Tél: +221 33 865 31 31 / +221 33 865 32 93.",
    rawContact: "SenegalBusinessSupport@pumaenergy.freshdesk.com | pumaenergy.com/careers/",
    contactType: "email",
    email: "SenegalBusinessSupport@pumaenergy.freshdesk.com",
    externalLink: "https://pumaenergy.com/careers/",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Carburants & Lubrifiants", "Aviation", "Vente au détail", "Énergie propre"],
  },
  {
    id: "touba-oil-sau",
    slug: "touba-oil-sau",
    company: "Touba Oil SAU",
    title: "Candidature Spontanée - Touba Oil SAU",
    domains: "Énergie, Hydrocarbures, Distribution (Candidature spontanée)",
    location: "Siège KM 18 Route de Rufisque, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Touba Oil SAU recrute pour la distribution de gaz et d'hydrocarbures. Tél: +221 33 879 87 16 / +221 76 529 27 15.",
    rawContact: "toubagaz@touba-oil.com | touba-oil.sn/contact/",
    contactType: "email",
    email: "toubagaz@touba-oil.com",
    externalLink: "https://touba-oil.sn/contact/",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Hydrocarbures", "Gaz & Distribution", "Réseau commercial"],
  },
  {
    id: "clean-oil-senegal",
    slug: "clean-oil-senegal",
    company: "Clean Oil (Sénégal)",
    title: "Candidature Spontanée - Clean Oil (Sénégal)",
    domains: "Énergie, Hydrocarbures, Énergie renouvelable, Eau, Assainissement",
    location: "Direction Générale Face Stade Amadou Barry, Guédiawaye, BP 18010, Dakar",
    contract_type: "Candidature Spontanée",
    description: "Clean Oil Sénégal recrute dans les hydrocarbures, l'énergie renouvelable, l'eau et l'assainissement. Tél: (221) 33 837 26 26 / Fax: (221) 33 837 33 33.",
    rawContact: "cleanoil-sn.com | Tél: (221) 33 837 26 26",
    contactType: "url",
    externalLink: "https://cleanoil-sn.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Hydrocarbures", "Énergie renouvelable", "Eau & Assainissement"],
  },
  {
    id: "eydon-petroleum",
    slug: "eydon-petroleum",
    company: "Eydon Petroleum",
    title: "Candidature Spontanée - Eydon Petroleum",
    domains: "Station-service, Énergie, Distribution (Candidature spontanée)",
    location: "Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Eydon Petroleum recrute pour son réseau de stations-services et la distribution pétrolière au Sénégal. Tél: 33 889 51 70.",
    rawContact: "eydon.com/contact | Tél: 33 889 51 70",
    contactType: "url",
    externalLink: "https://eydon.com/contact",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Station-service", "Distribution énergie", "Exploitation"],
  },
  {
    id: "mka-excellence",
    slug: "mka-excellence",
    company: "MKA Excellence",
    title: "Candidature Spontanée - MKA Excellence",
    domains: "Station-service, Restaurant, Entretien – Lavage, Vidange, Graissage, Boutique, Transfert d'argent",
    location: "Avenue Cheikh Ahmadou BAMBA, HLM x Rue 9 Bopp, BP 11474 Dakar",
    contract_type: "Candidature Spontanée",
    description: "MKA Excellence recrute pour ses stations multi-services : lavage, vidange, restaurant, boutique et transfert d'argent. Tél: (+221) 33 868 82 49 / (+221) 77 450 77 42.",
    rawContact: "contact@mkaexcellence.com | mkaexcellence.com",
    contactType: "email",
    email: "contact@mkaexcellence.com",
    externalLink: "https://mkaexcellence.com/?page_id=415",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Station multi-services", "Lavage & Vidange", "Restauration", "Boutique & Transfert"],
  },

  // --- HÔTELS & RESORTS (DAKAR, PETITE-CÔTE, SAINT-LOUIS, SALOUM, CASAMANCE) ---
  {
    id: "noom-hotel-dakar",
    slug: "noom-hotel-dakar",
    company: "Noom Hotel Dakar",
    title: "Candidature Spontanée - Noom Hotel Dakar",
    domains: "Hôtellerie de luxe, Réception, Restauration, Cuisine, Support IT, RH",
    location: "Corniche Ouest, Dakar Plateau, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Noom Hotel Dakar (Hôtel 5 étoiles) recrute en hôtellerie de luxe, réception, cuisine, gouvernance et services généraux.",
    rawContact: "noomhotels.com",
    contactType: "url",
    externalLink: "https://noomhotels.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Hôtellerie de luxe", "Réception", "Restauration", "Cuisine"],
  },
  {
    id: "radisson-blu-dakar",
    slug: "radisson-blu-dakar",
    company: "Radisson Blu Hotel Dakar",
    title: "Candidature Spontanée - Radisson Blu Hotel Dakar",
    domains: "Hôtellerie 5 étoiles, Service en salle, Cuisine, Maintenance, Réception",
    location: "Corniche Ouest, Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Postulez auprès du Radisson Blu Hotel Dakar pour des opportunités en hôtellerie internationale, service banquet et restauration.",
    rawContact: "radissonhotels.com",
    contactType: "url",
    externalLink: "https://radissonhotels.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Hôtellerie 5 étoiles", "Service banquet", "Cuisine", "Réception"],
  },
  {
    id: "king-fahd-palace",
    slug: "king-fahd-palace",
    company: "King Fahd Palace",
    title: "Candidature Spontanée - King Fahd Palace",
    domains: "Hôtellerie & Palais des Congrès, Restauration, Sécurité, Maintenance, Evénementiel",
    location: "Les Almadies, Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Le King Fahd Palace Hotel & Palais des Congrès accueille vos candidatures pour l'hôtellerie, la restauration d'affaires et l'événementiel.",
    rawContact: "kingfahdpalacehotels.com",
    contactType: "url",
    externalLink: "https://kingfahdpalacehotels.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Hôtellerie & Congrès", "Restauration", "Événementiel", "Sécurité"],
  },
  {
    id: "azalai-hotel-dakar",
    slug: "azalai-hotel-dakar",
    company: "Azalaï Hôtel Dakar",
    title: "Candidature Spontanée - Azalaï Hôtel Dakar",
    domains: "Hôtellerie d'affaires, Hébergement, Restauration, Réception, Commercial",
    location: "Corniche Ouest, Dakar, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Azalaï Hôtel Dakar recrute des profils qualifiés pour l'accueil, la restauration, la cuisine et la gestion d'hébergement.",
    rawContact: "azalaihotels.com",
    contactType: "url",
    externalLink: "https://azalaihotels.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Hôtellerie d'affaires", "Hébergement", "Réception", "Restauration"],
  },
  {
    id: "movenpick-lamantin-saly",
    slug: "movenpick-lamantin-saly",
    company: "Mövenpick Resort Lamantin Saly",
    title: "Candidature Spontanée - Mövenpick Resort Lamantin Saly",
    domains: "Resort balnéaire, Spa, Restauration, Animation, Gouvernance, Cuisine",
    location: "Saly Portudal, La Petite-Côte, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Mövenpick Resort Lamantin Saly recrute en hôtellerie d'exception, animation touristique, soins spa et restauration haut de gamme.",
    rawContact: "movenpick.com",
    contactType: "url",
    externalLink: "https://movenpick.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Resort balnéaire", "Spa & Bien-être", "Restauration", "Animation"],
  },
  {
    id: "hotel-riu-baobab",
    slug: "hotel-riu-baobab",
    company: "Hotel Riu Baobab (Pointe-Sarène)",
    title: "Candidature Spontanée - Hotel Riu Baobab",
    domains: "Hôtellerie Tout-Compris (All Inclusive), Restauration, Animation, Réception, Entretien",
    location: "Pointe-Sarène, La Petite-Côte, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "L'Hôtel Riu Baobab (Pointe-Sarène) recrute pour son complexe hôtelier balnéaire en All Inclusive : cuisine, service, animation et accueil.",
    rawContact: "riu.com",
    contactType: "url",
    externalLink: "https://riu.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Complexe balnéaire", "All Inclusive", "Animation", "Restauration"],
  },
  {
    id: "club-med-cap-skirring",
    slug: "club-med-cap-skirring",
    company: "Club Med Cap Skirring",
    title: "Candidature Spontanée - Club Med Cap Skirring",
    domains: "Village vacances, GO / GE, Restauration, Sports & Loisirs, Animation, Maintenance",
    location: "Cap Skirring, Casamance, Sénégal",
    contract_type: "Saisonnier & Permanent",
    description: "Club Med Cap Skirring recrute des G.O et G.E dans les sports nautiques, l'animation, la restauration, la cuisine et le service.",
    rawContact: "clubmed.fr",
    contactType: "url",
    externalLink: "https://clubmed.fr",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Village vacances", "Sports & Loisirs", "Animation GO/GE", "Restauration"],
  },
  {
    id: "hotel-kadiandoumagne-ziguinchor",
    slug: "hotel-kadiandoumagne-ziguinchor",
    company: "Hôtel Kadiandoumagne (Ziguinchor)",
    title: "Candidature Spontanée - Hôtel Kadiandoumagne",
    domains: "Hôtellerie au bord du fleuve, Réception, Restauration, Excursions",
    location: "Ziguinchor, Casamance, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "L'Hôtel Kadiandoumagne à Ziguinchor recrute en hôtellerie et restauration au cœur de la Casamance.",
    rawContact: "hotel-kadiandoumagne.com",
    contactType: "url",
    externalLink: "https://hotel-kadiandoumagne.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Hôtellerie Casamance", "Réception", "Restauration", "Tourisme"],
  },
  {
    id: "la-residence-saint-louis",
    slug: "la-residence-saint-louis",
    company: "La Résidence (Saint-Louis)",
    title: "Candidature Spontanée - Hôtel La Résidence Saint-Louis",
    domains: "Hôtel historique colonial, Restauration, Réception, Service client",
    location: "Île de Saint-Louis, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Hôtel d'exception situé sur l'Île de Saint-Louis recrutant des profils passionnés par l'hôtellerie de charme et la gastronomie.",
    rawContact: "hotellaresidence.com",
    contactType: "url",
    externalLink: "https://hotellaresidence.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Hôtellerie de charme", "Saint-Louis", "Restauration", "Réception"],
  },
  {
    id: "les-paletuviers-toubacouta",
    slug: "les-paletuviers-toubacouta",
    company: "Les Palétuviers (Toubacouta)",
    title: "Candidature Spontanée - Les Palétuviers Toubacouta",
    domains: "Écolodge de luxe, Saloum, Safari, Restauration, Service client",
    location: "Toubacouta, Sine Saloum, Sénégal",
    contract_type: "Candidature Spontanée",
    description: "Les Palétuviers à Toubacouta recrute pour son lodge haut de gamme au Sine Saloum : guidage touristique, cuisine, hébergement.",
    rawContact: "paletuviers.com",
    contactType: "url",
    externalLink: "https://paletuviers.com",
    documentsRequired: "CV, Lettre de motivation",
    image_url: null,
    poles: ["Écolodge de luxe", "Sine Saloum", "Guidage touristique", "Cuisine"],
  },
];

